# Generated by Django 4.1.7 on 2023-03-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPTConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('openAI_API_Key', models.CharField(max_length=200)),
                ('bot_Key', models.CharField(max_length=200)),
                ('history', models.TextField(default='[]')),
                ('total_token', models.IntegerField(default=0)),
            ],
        ),
    ]
