# Generated by Django 4.1.7 on 2023-03-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptconfiguration',
            name='base_url',
            field=models.CharField(default='http://127.0.0.1:5001', max_length=256),
        ),
        migrations.AddField(
            model_name='chatgptconfiguration',
            name='default_save_path',
            field=models.CharField(default='', max_length=256),
        ),
    ]
